name: maven

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '8.0.392+8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean package
