name: maven

on:
  # push:
  #   branches: [ "actions-github" ]
  release:
      types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '8.0.392+8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        mvn clean package
        ls target/plugin
        echo "versao=target/plugin/kafka-connect-lambda-localstack-${{ github.event.release.tag_name }}.jar"
    - name: Upload jar to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: target/plugin/kafka-connect-lambda-localstack-1.3.1.jar application/java-archive
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}